language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - android-25
sudo: required
before_script: 
  - chmod +x gradlew
    
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: "./gradlew $TASK"
env:
    - TASK="build -x lint"

branches:
  except:
  - l10n_master
  - l10n_master2
  - crowdin
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  slack: teamdorkaholics:waf6WiEhecMtC4t7N1Ju7xJS

after_success:
  - bash <(curl -s https://codecov.io/bash)
