files:
  - source: /app/src/main/res/values/strings*.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        es-ES: es       # Espanol
        de: de          # German
        ru: ru          # Russian
        pl: pl          # Polish
        ja: ja          # Japanese
        it: it          # Italian
        fr: fr          # French
        nl: nl          # Dutch
        hu: hu          # Hungarian
        cs: cs          # Czech
        sr: sr          # Serbian (Cyrillic)
        pt-PT: pt       # Portugese
        pt-BR: pt-rBR   # Portugese (Brazilian)
        zh-CN: zh-rCN   # Chinese (Simplified)